In [1]:
import numpy as np#3x4
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
print(a)
s=a.shape
s1=a.size
print("\nShape=",s)
print("\nSize=",s1)

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

Shape= (3, 4)

Size= 12


In [2]:
import numpy as np
a = np.array([[1,2],[2,4],[10,20]])
print(a)
s=a.shape
s1=a.size
print("\nShape=",s)
print("\nSize=",s1)

[[ 1  2]
 [ 2  4]
 [10 20]]

Shape= (3, 2)

Size= 6


In [4]:
import numpy as np#3x4
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3],[1,2,3,4],[1,2,3,4]])
print(a)
s=a.shape
s1=a.size
print("\nShape=",s)
print("\nSize=",s1)

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]
 [ 1  2  3  4]
 [ 1  2  3  4]]

Shape= (5, 4)

Size= 20


In [5]:
#math
import numpy as np#3x4
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
c=a+1
print(c)

[[ 2  3  4  5]
 [ 3  5  6  7]
 [11 21 40  4]]


In [6]:
#math
import numpy as np#3x4
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
c=a/3
print(c)

[[ 0.33333333  0.66666667  1.          1.33333333]
 [ 0.66666667  1.33333333  1.66666667  2.        ]
 [ 3.33333333  6.66666667 13.          1.        ]]


In [7]:
import numpy as np#3x4
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
b= np.array([[11,21,31,4],[21,14,5,6],[10,210,319,31]])
c=a+1
add=a+b
print(add)

[[ 12  23  34   8]
 [ 23  18  10  12]
 [ 20 230 358  34]]


In [8]:
import numpy as np#3x4
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
b= np.array([[11,21,31,4],[21,14,5,6],[10,210,319,31]])
c=a+b
print(c)
a=a>b
print(a)

[[ 12  23  34   8]
 [ 23  18  10  12]
 [ 20 230 358  34]]
[[False False False False]
 [False False False False]
 [False False False False]]


In [9]:
import numpy as np
import pandas as pd
a = np.array([[1, 2, 3, 4], [2, 4, 5, 6], [10, 20, 39, 3]])

# Convert the matrix to a Pandas DataFrame
df = pd.DataFrame(a, columns=['Col1', 'Col2', 'Col3', 'Col4'])
print(df)


   Col1  Col2  Col3  Col4
0     1     2     3     4
1     2     4     5     6
2    10    20    39     3


In [13]:
#slice
import numpy as np#3x4
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])

c=a[0,3]
print(c)

4


In [14]:
import numpy as np#sort
x = np.array([[10,2,3,4],[20,4,5,6],[10,20,39,3]])
print("Original mat:")
print(x)
print("sort:")
y = np.sort(x)
print(y)

Original mat:
[[10  2  3  4]
 [20  4  5  6]
 [10 20 39  3]]
sort:
[[ 2  3  4 10]
 [ 4  5  6 20]
 [ 3 10 20 39]]


In [15]:
import numpy as np#sort
x = np.array([[10,2,3,4],[20,4,5,6],[10,20,39,3]])
print("Original mat:")
print(x)

y = np.min(x)
z=np.max(x)
a=np.mean(x)
print("Min",y)
print("Average",a)
print("max",z)

Original mat:
[[10  2  3  4]
 [20  4  5  6]
 [10 20 39  3]]
Min 2
Average 10.5
max 39


In [16]:
import numpy as np#reverse
x = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
print("Original mat:")
print(x)
print("Reverse mat:")
y = x[::-1]# -1 inside colon
print(y)

Original mat:
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]
Reverse mat:
[[10 20 39  3]
 [ 2  4  5  6]
 [ 1  2  3  4]]


In [17]:
#V Dot(normal mutiply)

#A and B  V Dot
#1   2	         11   12
#3   4          13   14

#(A11xB11)  +  (A12xB12)  +  (A21xB21)  + (A22xB22)
#Note − 1*11 + 2*12 + 3*13 + 4*14 = 130


import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
c= np.vdot(a,b)
print(c)

130
