In [1]:
import numpy as np
x = np.random.rand(10)# one dimension array
print(x)

[0.21556125 0.80164027 0.84365466 0.78896701 0.67816043 0.2064021
 0.64663093 0.01731564 0.74113119 0.41616479]


In [2]:
import numpy as np
x = np.random.rand(100)# one dimension array
print(x)

[0.77906795 0.60511509 0.4439953  0.92410954 0.89365596 0.01148037
 0.85815253 0.77511157 0.10769379 0.46082187 0.93660775 0.59831749
 0.43921775 0.48184163 0.9393305  0.46923347 0.3506337  0.811625
 0.44555975 0.89907297 0.5922894  0.78035245 0.49279157 0.498966
 0.98981726 0.52946226 0.46521322 0.29469901 0.65847623 0.90449677
 0.78834718 0.92541819 0.93381454 0.60906766 0.02977166 0.99185052
 0.27671198 0.74288349 0.30892284 0.7599314  0.11865479 0.79438384
 0.88211393 0.9329237  0.23020755 0.5069279  0.80812462 0.0244862
 0.94758206 0.54118872 0.71733606 0.1133654  0.63515051 0.23027029
 0.83968906 0.88248632 0.39159982 0.1197383  0.70102216 0.50237891
 0.48146815 0.05543757 0.42149791 0.9909849  0.26926177 0.15555469
 0.9564754  0.20746604 0.79967621 0.28489052 0.68464699 0.22535257
 0.27168289 0.95090716 0.43281117 0.1748698  0.75273052 0.76998645
 0.48254513 0.77902684 0.89987507 0.53831407 0.98226877 0.64988612
 0.66373231 0.39014982 0.10776834 0.87417254 0.91241679 0.11653246


In [3]:
#Shuffle
from numpy import random
import numpy as np
a= np.array([1, 2, 3, 4, 5])
random.shuffle(a)
print(a)

[5 4 3 2 1]


In [3]:
import numpy as np
# Initialize random number generator
rng = np.random.default_rng()
# Generate random integers between 1 and 2 (inclusive)
num_records = 10
random_numbers = rng.integers(1,  6, size=num_records)
print(random_numbers)

[4 3 2 2 5 3 4 4 2 1]


In [5]:
#float cant be given
import numpy as np
# Initialize random number generator
rng = np.random.default_rng()
# Generate random floating-point numbers between 1 and 3
num_records = 10
random_numbers = rng.uniform(1, 3, size=num_records)
print(random_numbers)

[2.76328463 2.34856464 1.72216763 1.75203348 1.18770254 2.63503014
 2.54000328 1.06332793 2.58976849 2.29961805]


In [4]:
import numpy as np# Generate 10 unique random integers between 1 and 100

# Initialize random number generator
rng = np.random.default_rng()
num_records = 10
unique_integers = rng.choice(np.arange(0, 101), size=num_records, replace=False)
print(unique_integers)

[64 20  3 47 35 82 53 83  4 70]


In [7]:
#names
import numpy as np

rng = np.random.default_rng()
name_list = ["John", "Alice",  "Sophia", "Liam", "Emma", "Noah", "Olivia", "James", "Mia"]
num_records = 10
# Generate random names by selecting from the name_list
random_names = rng.choice(name_list, size=num_records, replace=True)
print(random_names)

['Olivia' 'Alice' 'Olivia' 'Mia' 'Liam' 'Sophia' 'Sophia' 'Noah' 'John'
 'Mia']


In [5]:
#ML sales 15 data
import numpy as np
from numpy import random
import pandas as pd
def name():
    arr = ['Arun', 'Akash', 'Sanjay', 'Manu']
    n=np.random.choice(arr, 15, p=[0.5, 0.1, 0.1, 0.3])
    return n
def month():
    m1 = random.choice([1,2,3,4,5,6,7,8,9,10,11,12], p=[0.1, 0.1, 0.1, 0.1,0.1,0.1,0.1, 0.1, 0.05, 0.05,0.05,0.05], size=(15))
    return m1
def id():
    id = np.arange(15)
def unitprice():
     x = np.random.rand(15)
     x1=x*1000
     unit = np.round(x1, decimals=0)
     return unit
def quan():
    y = random.uniform(size=(15))
    y1=y*100
    q = np.round(y1, decimals=0)
    return q
def location():
    country_names = ["USA", "Canada", "UK", "Germany", "France", "Japan", "Australia"]
    c=np.random.choice(country_names, 15, p=[0.3, 0.1, 0.1, 0.1,0.1,0.1,0.2])
    return c
def coustomerid():
    z = np.arange(300, 320)
    x = random.choice(z, p=[0.05]*len(z), size=(15))
    return x
def prodid():
    y = random.uniform(size=(15))
    y1=y*100
    p = np.round(y1, decimals=2)
    np.random.shuffle(p)
    return p
def storeid():
    z = np.arange(1300, 1320)
    x = random.choice(z, p=[0.05]*len(z), size=(15))
    return x
def storesize():
    arr = ['Premium', 'Branded', 'Valueformoney', 'Economy','Sale','Factoryoutlet','Retail']
    n=np.random.choice(arr, 15, p=[0.2, 0.1, 0.1, 0.2,0.1,0.2,0.1])
    return n
def closetime():
    ohrs1 = random.choice([21,22,23,20], p=[0.2, 0.2, 0.2, 0.4], size=(15))
    return ohrs1
def adv():#advertise rating star
    adv=random.choice([1,2,3,4,5], p=[0.2, 0.2, 0.2, 0.2,0.2], size=(15))
    return adv

def com():#competetor price
    com=random.choice(["High","Low","Equal"], p=[0.2, 0.2, 0.6], size=(15))
    return com
def sup():#supply
    sup=random.choice(["Surplus","LowStock","StockAvailable"], p=[0.2, 0.2, 0.6], size=(15))
    return sup
def paytype():
    pay=random.choice(["CreditCard","DebitCard","Cash","UPI","EMI"], p=[0.4, 0.1, 0.1,0.1,0.3], size=(15))
    return pay
def profit():#profit in per
    profit=random.choice([10,15,5,20,25], p=[0.4, 0.1, 0.1,0.1,0.3], size=(15))
    return profit
def feedback():
    feed=random.choice([1,2,3,4,5], p=[0.2, 0.2, 0.2, 0.2,0.2], size=(15))
    return feed

def infra():
    infra=random.choice(["Own","Rented", "Sponsored"], p=[0.2, 0.5, 0.3], size=(15))
    return infra
def parking():
    park=random.choice(["Spacious","Available", "NotAvailable"], p=[0.2, 0.5, 0.3], size=(15))
    return park
def emp():
    emp=random.choice(["50+","below_50", "100+"], p=[0.2, 0.5, 0.3], size=(15))
    return emp
name=name()
month=month()
price=unitprice()
Q=quan()
L=location()
cid=coustomerid()
pid=prodid()
sid=storeid()
storesize=storesize()
closetime=closetime()
a=adv()#advertisement
c=com()#competetor price
supply=sup()#supply
payment=paytype()
profit=profit()
feedb=feedback()
infra=infra()
parking=parking()
emp=emp()
frame = {
    "StoreID": sid,
    "StoreSize": storesize,
    "Parking": parking,
    "ClosingTime": closetime,
    "Month": month,
    "CustomerID": cid,
    "ProductID": pid,
    "UnitPrice": price,
    "Quantity": Q,
    "CompetitorPrice": c,
    "Supply": supply,
    "Profit_percentage": profit,
    "Advertisementstar": a,
    "PaymentType": payment,
    "Employee": emp,
    "Feedbackstar": feedb
}
dfsales=pd.DataFrame(frame)
print(dfsales)
dfsales.to_excel('sales1.xlsx', index=False)

    StoreID      StoreSize       Parking  ClosingTime  Month  CustomerID  \
0      1306        Economy     Available           21      3         306   
1      1313           Sale      Spacious           20      5         316   
2      1313           Sale     Available           22      6         303   
3      1316        Economy      Spacious           20      4         316   
4      1308  Factoryoutlet     Available           20      7         303   
5      1316         Retail     Available           20      7         306   
6      1314  Factoryoutlet  NotAvailable           20      8         317   
7      1304  Factoryoutlet      Spacious           22      4         300   
8      1300        Branded     Available           21      7         308   
9      1305  Valueformoney     Available           20      8         301   
10     1300  Factoryoutlet     Available           21      5         311   
11     1310  Valueformoney  NotAvailable           21      4         313   
12     1304 